name: Publish to npm registry

on: [release]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm run lint
      env:
        CI: true
    - name: npm publish --dry-run
      run: |
        npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
        npm publish
      env:
        CI: true
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
